/**
 * @packageDocumentation
 * @module api.functional.bbs.managers.authenticate
 */
//================================================================
import { AesPkcs5 } from "./../../../../__internal/AesPkcs5";
import { Fetcher } from "./../../../../__internal/Fetcher";
import { Primitive } from "./../../../../Primitive";
import type { IConnection } from "./../../../../IConnection";

import type { IBbsManager } from "./../../../../structures/bbs/actors/IBbsManager";
import type { IMember } from "./../../../../structures/members/IMember";

export * as password from "./password";

/**
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 * @controller BbsManagerAuthenticateController.get()
 * @path GET /bbs/managers/authenticate/
 */
export function get(connection: IConnection, ): Promise<get.Output>
{
    return Fetcher.fetch
    (
        connection,
        {"input_encrypted":false,"output_encrypted":true},
        "GET",
        `/bbs/managers/authenticate/`
    );
}
export namespace get
{
    export type Output = Primitive<IBbsManager>;
}

/**
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 * @controller BbsManagerAuthenticateController.join()
 * @path POST /bbs/managers/authenticate/join
 */
export function join(connection: IConnection, input: Primitive<join.Input>): Promise<join.Output>
{
    return Fetcher.fetch
    (
        connection,
        {"input_encrypted":true,"output_encrypted":true},
        "POST",
        `/bbs/managers/authenticate/join`,
        input
    );
}
export namespace join
{
    export type Input = Primitive<IMember.IJoin>;
    export type Output = Primitive<IBbsManager>;
}

/**
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 * @controller BbsManagerAuthenticateController.login()
 * @path POST /bbs/managers/authenticate/login
 */
export function login(connection: IConnection, input: Primitive<login.Input>): Promise<login.Output>
{
    return Fetcher.fetch
    (
        connection,
        {"input_encrypted":true,"output_encrypted":true},
        "POST",
        `/bbs/managers/authenticate/login`,
        input
    );
}
export namespace login
{
    export type Input = Primitive<IMember.ILogin>;
    export type Output = Primitive<IBbsManager>;
}

/**
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 * @controller BbsManagerAuthenticateController.refresh()
 * @path GET /bbs/managers/authenticate/refresh
 */
export function refresh(connection: IConnection, ): Promise<refresh.Output>
{
    return Fetcher.fetch
    (
        connection,
        {"input_encrypted":false,"output_encrypted":true},
        "GET",
        `/bbs/managers/authenticate/refresh`
    );
}
export namespace refresh
{
    export type Output = Primitive<object>;
}



//---------------------------------------------------------
// TO PREVENT THE UNUSED VARIABLE ERROR
//---------------------------------------------------------
AesPkcs5;
Fetcher;
Primitive;
