/**
 * @packageDocumentation
 * @module api.functional.bbs.admins.articles.reviews
 */
//================================================================
import { AesPkcs5 } from "./../../../../../__internal/AesPkcs5";
import { Fetcher } from "./../../../../../__internal/Fetcher";
import { Primitive } from "./../../../../../Primitive";
import type { IConnection } from "./../../../../../IConnection";

import type { IBbsArticle } from "./../../../../../structures/bbs/articles/IBbsArticle";
import type { IBbsReviewArticle } from "./../../../../../structures/bbs/articles/IBbsReviewArticle";
import type { IPage } from "./../../../../../structures/common/IPage";


/**
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 * @controller BbsAdminArticleReviewsController.index()
 * @path PATCH /bbs/admins/articles/reviews/:code/
 */
export function index(connection: IConnection, code: string, input: Primitive<index.Input>): Promise<index.Output>
{
    return Fetcher.fetch
    (
        connection,
        {"input_encrypted":true,"output_encrypted":true},
        "PATCH",
        `/bbs/admins/articles/reviews/${code}/`,
        input
    );
}
export namespace index
{
    export type Input = Primitive<IBbsArticle.IRequest<IBbsReviewArticle.IRequest.ISearch>>;
    export type Output = Primitive<IPage<IBbsReviewArticle.ISummary>>;
}

/**
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 * @controller BbsAdminArticleReviewsController.at()
 * @path GET /bbs/admins/articles/reviews/:code/:id
 */
export function at(connection: IConnection, code: string, id: string): Promise<at.Output>
{
    return Fetcher.fetch
    (
        connection,
        {"input_encrypted":false,"output_encrypted":true},
        "GET",
        `/bbs/admins/articles/reviews/${code}/${id}`
    );
}
export namespace at
{
    export type Output = Primitive<IBbsReviewArticle>;
}



//---------------------------------------------------------
// TO PREVENT THE UNUSED VARIABLE ERROR
//---------------------------------------------------------
AesPkcs5;
Fetcher;
Primitive;
