/**
 * @packageDocumentation
 * @module api.functional.bbs.admins.authenticate
 */
//================================================================
import { AesPkcs5 } from "./../../../../__internal/AesPkcs5";
import { Fetcher } from "./../../../../__internal/Fetcher";
import { Primitive } from "./../../../../Primitive";
import type { IConnection } from "./../../../../IConnection";

import type { IMember } from "./../../../../structures/members/IMember";

export * as password from "./password";

/**
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 * @controller BbsAdminAuthenticateController.get()
 * @path GET /bbs/admins/authenticate/
 */
export function get
    (
        connection: IConnection
    ): Promise<get.Output>
{
    return Fetcher.fetch
    (
        connection,
        {
            input_encrypted: false,
            output_encrypted: true
        },
        "GET",
        `/bbs/admins/authenticate/`
    );
}
export namespace get
{
    export type Output = Primitive<IMember>;
}

/**
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 * @controller BbsAdminAuthenticateController.login()
 * @path POST /bbs/admins/authenticate/login
 */
export function login
    (
        connection: IConnection,
        input: Primitive<login.Input>
    ): Promise<login.Output>
{
    return Fetcher.fetch
    (
        connection,
        {
            input_encrypted: true,
            output_encrypted: true
        },
        "POST",
        `/bbs/admins/authenticate/login`,
        input
    );
}
export namespace login
{
    export type Input = Primitive<IMember.ILogin>;
    export type Output = Primitive<IMember>;
}

/**
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 * @controller BbsAdminAuthenticateController.refresh()
 * @path GET /bbs/admins/authenticate/refresh
 */
export function refresh
    (
        connection: IConnection
    ): Promise<refresh.Output>
{
    return Fetcher.fetch
    (
        connection,
        {
            input_encrypted: false,
            output_encrypted: true
        },
        "GET",
        `/bbs/admins/authenticate/refresh`
    );
}
export namespace refresh
{
    export type Output = Primitive<object>;
}



//---------------------------------------------------------
// TO PREVENT THE UNUSED VARIABLE ERROR
//---------------------------------------------------------
AesPkcs5;
Fetcher;
Primitive;
