/**
 * @packageDocumentation
 * @module api.functional.monitors.health
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

/**
 * @controller MonitorHealthController.get
 * @path GET /monitors/health
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function get(
    connection: IConnection,
): Promise<void> {
    return !!connection.simulate
        ? get.simulate(
              connection,
          )
        : PlainFetcher.fetch(
              connection,
              {
                  ...get.METADATA,
                  path: get.path(),
              } as const,
          );
}
export namespace get {

    export const METADATA = {
        method: "GET",
        path: "/monitors/health",
        request: null,
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: null,
    } as const;

    export const path = (): string => {
        return `/monitors/health`;
    }
    export const simulate = async (
        _connection: IConnection,
    ): Promise<void> => {
    }
}