/**
 * @packageDocumentation
 * @module api.functional.bbs.admins.articles.comments
 */
//================================================================
import { AesPkcs5 } from "./../../../../../__internal/AesPkcs5";
import { Fetcher } from "./../../../../../__internal/Fetcher";
import { Primitive } from "./../../../../../Primitive";
import type { IConnection } from "./../../../../../IConnection";

import type { IPage } from "./../../../../../structures/common/IPage";
import type { IBbsComment } from "./../../../../../structures/bbs/articles/IBbsComment";


/**
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 * @controller BbsAdminCommentsController.index()
 * @path PATCH /bbs/admins/articles/:type/:code/:id/comments/
 */
export function index(connection: IConnection, type: string, code: string, id: string, input: Primitive<index.Input>): Promise<index.Output>
{
    return Fetcher.fetch
    (
        connection,
        {"input_encrypted":true,"output_encrypted":true},
        "PATCH",
        `/bbs/admins/articles/${type}/${code}/${id}/comments/`,
        input
    );
}
export namespace index
{
    export type Input = Primitive<IPage.IRequest>;
    export type Output = Primitive<IPage<IBbsComment>>;
}



//---------------------------------------------------------
// TO PREVENT THE UNUSED VARIABLE ERROR
//---------------------------------------------------------
AesPkcs5;
Fetcher;
Primitive;
