name: build
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:16-3.4
        env:
          POSTGRES_PASSWORD: root
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v4

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Create DB Schema
        working-directory: packages/backend
        run: pnpm schema postgres root

      - name: Test
        working-directory: packages/backend
        run: pnpm test --reset true --simultaneous 16
