name: "Dependabot Automerge"
on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize]
    paths:
      - "package.json"
      - "packages/api/package.json"
jobs:
  build-and-merge:
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Comment on PR
        run: |
          gh pr comment "$PR_URL" --body "@dependabot merge"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.DEPENDABOT_AUTOMERGE_GITHUB_TOKEN }}
